-- Fetch all of the data from the table.
-- SELECT * FROM students
-- 2. Fetch all of the students first_names and last_names.
-- SELECT first_name, last_name FROM students
-- 3. For the following questions, only fetch the first_names and last_names of the students.
--  Fetch the student which id is equal to 2.
-- SELECT first_name, last_name FROM students where id = 2
--  Fetch the student whose last_name is Benichou AND first_name is Marc.
-- SELECT first_name, last_name FROM students where last_name = 'Benichou' and first_name = 'Marc'
--  Fetch the students whose last_names are Benichou OR first_names are Marc.
-- SELECT first_name, last_name FROM students where last_name = 'Benichou' or first_name = 'Marc'
--  Fetch the students whose first_names contain the letter a.
-- SELECT first_name, last_name FROM students where first_name like '%a%'
--  Fetch the students whose first_names start with the letter a.
-- SELECT first_name, last_name FROM students where first_name like 'A%'
--  Fetch the students whose first_names end with the letter a.
-- SELECT first_name, last_name FROM students where first_name like '%a'
--  Fetch the students whose second to last letter of their first_names are a (Example: Leah).
-- SELECT first_name, last_name FROM students where first_name like '%a_'
--  Fetch the students whose id’s are equal to 1 AND 3 .
-- SELECT first_name, last_name FROM students where id in (1,3)
-- 4. Fetch the students whose birth_dates are equal to or come after 1/01/2000. (show all their info).
-- SELECT * FROM students where birth_date >= '01/01/2000'